namespace IbkrTradeRepository.PortalApp.Domain
{
    public record IbkrCode(string Code, string Description);

    public static class IbkrCodeSeedData
    {
        public static IbkrCode[] CodesSeedData =>
        [
            new IbkrCode("A", "Assignment"),
            new IbkrCode("ADR", "ADR Fee Accrual"),
            new IbkrCode("AEx", "Automatic exercise for dividend-related recommendation."),
            new IbkrCode("AFx", "AutoFX conversion resulting from trading"),
            new IbkrCode("Adj", "Adjustment"),
            new IbkrCode("Al", "Allocation"),
            new IbkrCode("Aw", "Away Trade"),
            new IbkrCode("B", "Automatic Buy-in"),
            new IbkrCode("Bo", "Direct Borrow"),
            new IbkrCode("C", "Closing Trade"),
            new IbkrCode("CD", "Cash Delivery"),
            new IbkrCode("CP", "Complex Position"),
            new IbkrCode("Ca", "Cancelled"),
            new IbkrCode("Co", "Corrected Trade"),
            new IbkrCode("Cx", "Part or all of this transaction was a Crossing executed as dual agent by IB for two IB customers"),
            new IbkrCode("DT", "Discounted Trade"),
            new IbkrCode("De", "Delivery or Conversion Action"),
            new IbkrCode("ETF", "ETF Creation/Redemption"),
            new IbkrCode("Ep", "Resulted from an Expired Position"),
            new IbkrCode("Ex", "Exercise"),
            new IbkrCode("FP", "The fractional portion of this trade was executed against IB or an affiliate."),
            new IbkrCode("FPA", "The fractional portion of this trade was executed against IB or an affiliate. IB acted as agent for the whole share portion of this trade."),
            new IbkrCode("G", "Trade in Guaranteed Account Segment"),
            new IbkrCode("GEA", "Exercise or Assignment resulting from offsetting positions"),
            new IbkrCode("HC", "Highest Cost tax basis election"),
            new IbkrCode("HFI", "Investment Transferred to Hedge Fund"),
            new IbkrCode("HFR", "Redemption from Hedge Fund"),
            new IbkrCode("I", "Internal Transfer"),
            new IbkrCode("IA", "The transaction was executed against IB or an affiliate"),
            new IbkrCode("IM", "A portion of the order was executed against IB or an affiliate; IB acted as agent on a portion."),
            new IbkrCode("INV", "Investment Transfer from Investor"),
            new IbkrCode("IPO", "This transaction was executed as part of an IPO in which IB was a member of the selling group and is classified as a Principal trade."),
            new IbkrCode("L", "Ordered by IB (Margin Violation)"),
            new IbkrCode("LD", "Adjusted by Loss Disallowed from Wash Sale"),
            new IbkrCode("LF", "Liquidation of fractional position by IB"),
            new IbkrCode("LI", "Last In, First Out (LIFO) tax basis election"),
            new IbkrCode("LT", "Long Term P/L"),
            new IbkrCode("Lo", "Direct Loan"),
            new IbkrCode("M", "Entered manually by IB"),
            new IbkrCode("MEx", "Manual exercise for dividend-related recommendation."),
            new IbkrCode("ML", "Maximize Losses tax basis election"),
            new IbkrCode("MLG", "Maximize Long Term Gain tax basis election"),
            new IbkrCode("MLL", "Maximize Long Term Loss tax basis election"),
            new IbkrCode("MSG", "Maximize Short Term Gain tax basis election"),
            new IbkrCode("MSL", "Maximize Short Term Loss tax basis election"),
            new IbkrCode("O", "Opening Trade"),
            new IbkrCode("Off", "Yes and No contracts offset to $1.00 cash settlement"),
            new IbkrCode("P", "Partial Execution"),
            new IbkrCode("PE", "Perpetual Investment"),
            new IbkrCode("PI", "Price Improvement"),
            new IbkrCode("PTA", "Post Trade Allocation"),
            new IbkrCode("Po", "Interest or Dividend Accrual Posting"),
            new IbkrCode("Pr", "Part or all of this transaction was executed by the Exchange as a Crossing by IB against an IB affiliate and is therefore classified as a Principal and not an agency trade"),
            new IbkrCode("R", "Dividend Reinvestment"),
            new IbkrCode("RED", "Redemption to Investor"),
            new IbkrCode("RI", "Recurring Investment"),
            new IbkrCode("RP", "IB acted as agent for the fractional share portion of this trade, which was executed by an IB affiliate as riskless principal."),
            new IbkrCode("RPA", "IB acted as agent for both the fractional share portion and the whole share portion of this trade; the fractional share portion was executed by an IB Affiliate as riskless principal."),
            new IbkrCode("Rb", "Rebill"),
            new IbkrCode("Re", "Interest or Dividend Accrual Reversal"),
            new IbkrCode("Ri", "Reimbursement"),
            new IbkrCode("S0", "Contract settled to zero value"),
            new IbkrCode("S1", "Contract settled to $1.00"),
            new IbkrCode("SF", "Trade is subject to IBKR Lite Surcharge Fee if volume of such trades exceeds 10% of the total monthly Lite trade volume"),
            new IbkrCode("SI", "This order was solicited by Interactive Brokers"),
            new IbkrCode("SL", "Specific Lot tax basis election"),
            new IbkrCode("SO", "This order was marked as solicited by your Introducing Broker"),
            new IbkrCode("SS", "Customer designated this trade for shortened settlement and so is subject to execution at prices above the prevailing market"),
            new IbkrCode("ST", "Short Term P/L"),
            new IbkrCode("T", "Transfer"),
            new IbkrCode("Un", "Unvested shares from stock grant"),
            new IbkrCode("XCH", "Mutual Fund Exchange Transaction")
        ];
    }
}
